apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  rules:
  - host: "{{ HOST }}"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: master-webapp-svc
            port:
              number: 80
  tls:
  - secretName: webapp-ing-cert
    hosts: 
    - "{{ HOST }}"
